### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by dev-sheikh-ali** [abdulrcs/abdulrahman.id#11]
Hey Abdulrahman
i have tried to run this project and i am not quite familiar with firebase could you please share a screenshot of the view you have created or a bit clearer instructions like the contentful ones.
i have also seen some random errors the site never loads e.g 
   
                  { sys: { type: 'Error', id: 'AccessTokenInvalid' },
                    message:
                     'The access token you sent could not be found or is invalid.',
                    requestId: '6adbb8ef-1637-4e3b-8235-64d9a92aaf44' }
                  Warning: Invalid DOM property `crossorigin`. Did you mean `crossOrigin`?
                      at link
                      at html
                      at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:158:29)
                      at MyDocument (webpack-internal:///./pages/_document.js:12:1)
                  Warning: Invalid event handler property `onload`. React events use the camelCase naming convention, for example `onClick`.
                      at link
                      at html
                      at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:158:29)
                      at MyDocument (webpack-internal:///./pages/_document.js:12:1)
                  { sys: { type: 'Error', id: 'AccessTokenInvalid' },
                    message:
i have put the right values in the `.env.local` file

**Comment by abdulrcs** [comment]
hey @dev-sheikh-ali, thanks for contributing by raising this issue.

That error message is a Contentful related error, it might be related to this commit 4ee3f8f5227c463c5b3404e387aefcc219d09dfe.
I have added a new content type and updated the documentation for it on the [readme](https://github.com/abdulrcs/abdulrahman.id#readme),
You can add the new content types in Contentful to resolve it.

As for the Firebase setup instructions, I will gladly accept a new pull request to improve the documentation.

**Comment by dev-sheikh-ali** [comment]
Thank you @abdulrcs ,
Eid mubarak

**Comment by atharva20-coder** [comment]
I am still getting the same message

**Comment by dreemhai** [comment]
@dev-sheikh-ali which node version do I need to use for running this code?

**Comment by dev-sheikh-ali** [comment]
> @dev-sheikh-ali which node version do I need to use for running this code?

heyy sorry for the late response , i used node v14.16.1
