### ISSUE TITLE
sys: { type: 'Error', id: 'InvalidQuery' }

### ISSUE THREAD

**Issue by cyberdev101** [abdulrcs/abdulrahman.id#13]
Hi, thanks for taking a look at my issue!

I'm fairly new to next.js, so I'm awful at debugging errors. Heres my error:

```
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
{
  sys: { type: 'Error', id: 'InvalidQuery' },
  message: 'The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.',
  details: { errors: [ [Object] ] },
  requestId: '929ea726-ef17-4ddb-9b92-f0b2da654413'
}
```

Any help is appreciated, and feel free to ask any questions (like my OS, though it didnt work on github codespaces, vercel, or locally.)

**Comment by cyberdev101** [comment]
Also have the issue of `Warning: Invalid DOM property "crossorigin". Did you mean "crossOrigin"?`. This appeared in both github codespaces and locally (along with the issue above)

Everytime I attempt to change it back to capital crossOrigin, it goes back to `origin` when I do npm run dev.

thanks!

**Comment by cyberdev101** [comment]
Never mind, I got the fix.

**Comment by Aarekaz** [comment]
How did you fix it?
